version: '3.8'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fit-bot-db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fit_bot-network

  fit_bot:
    image: fit_bot:latest
    container_name: fit_bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fit-bot-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      BOT_TOKEN: ...
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fit_bot-network

networks:
  fit_bot-network:
    driver: bridge

volumes:
  postgres_data:


